on:
  pull_request:
  push:
    branches: [main]

jobs:
  cargo-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Leafwing-Studios/cargo-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - name: Cargo test
        run: cargo hack test --feature-powerset --mutually-exclusive-features std,libm

  cargo-clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Leafwing-Studios/cargo-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - name: Cargo clippy
        run: cargo hack clippy --feature-powerset --mutually-exclusive-features std,libm -- -D warnings

  cargo-fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cargo fmt
        run: cargo fmt --all --check
